---
- name: Create loop device image
  shell: |
    mkdir -p {{ loopback_image | dirname }}
    truncate -s {{ loopback_image_size }} {{ loopback_image }}

- name: Create loop device
  shell: |
    mknod {{ loopback_device }} b $(grep loop /proc/devices | cut -c3) {{ loopback_device | regex_search('[0-9]+') }}

- name: Create loop-setup systemd unit
  template:
    src: files/loop-setup.service
    dest: /etc/systemd/system/loop-setup.service
  notify:
    - Systemd reload

- name: Systemd reload
  shell: systemctl daemon-reload

- name: Configure loop-setup systemd unit
  service:
    name: loop-setup
    enabled: yes
    state: started
  notify:
    - Systemd reload
    - Restart loop-setup

- name: Check {{ loopback_device }} is attached
  shell: |
    losetup | grep -i {{ loopback_device }}
...
