version = 2
disabled_plugins = []
[plugins."io.containerd.grpc.v1.cri".registry]
config_path = "/etc/containerd/certs.d"

{% for item in registry_namespaces %}
{% if item.auth is defined %}
[plugins."io.containerd.grpc.v1.cri".registry.configs."{{ item.namespace }}".auth]
auth = "{{ item.auth }}"
{% endif %}
{% endfor %}